language: node_js

node_js:
  - "4"

sudo: false

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    - dist/assets/images # optimized images

addons:
  ssh_known_hosts: new-mademistakes.com
  apt_packages:
    - graphicsmagick

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm install 2.2
  - rvm use 2.2
  - . $HOME/.nvm/nvm.sh && nvm install 4.4 && nvm use 4.4
  - gem install bundler

install:
  - bundle install
  - npm install

script: gulp build --prod

before_deploy:
  - mkdir /tmp
  - openssl aes-256-cbc -K $encrypted_f55b475b43f3_key -iv $encrypted_f55b475b43f3_iv -in deploy_keys.tar.enc -out /tmp/deploy_keys.tar -d
  - tar -xvf /tmp/deploy_keys.tar -C /tmp/
  - mv /tmp/rsync-credentials.json rsync-credentials.json
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: master

