language: node_js
node_js:
  - "4"
cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    - dist/assets/images # optimized images
before_install:
  - sudo apt-get install graphicsmagick
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - rvm install 2.2
  - rvm use 2.2
  - . $HOME/.nvm/nvm.sh && nvm install 4.4 && nvm use 4.4
  - gem install bundler
  - bundle check || bundle install
install:
  - npm install
script: gulp build --prod
